lr0: 0.0008
lrf: 0.005
momentum: 0.95
weight_decay: 0.0003
warmup_epochs: 8.0
warmup_momentum: 0.85
warmup_bias_lr: 0.05
box: 8.5
cls: 0.8
dfl: 2.0
hsv_h: 0.02
hsv_s: 0.8
hsv_v: 0.5
degrees: 15.0
translate: 0.25
scale: 0.95
shear: 3.0
perspective: 0.0002
flipud: 0.6
fliplr: 0.6
mosaic: 1.0
mixup: 0.2
copy_paste: 0.4
anchor_t: 5.0
anchors: 3
fl_gamma: 0.5
label_smoothing: 0.15
nbs: 64
overlap_mask: true
mask_ratio: 4
dropout: 0.0
optimizer: AdamW
cos_lr: true
close_mosaic: 15
auto_augment: randaugment
erasing: 0.5
crop_fraction: 1.0
seed: 42
deterministic: true
verbose: true
